### ISSUE TITLE
Digital assets-CMS issue

### ISSUE THREAD

**Issue by Aminshoshtaryzadeh** [entando/entando-components#295]
I installed CMS plugin, the issue is when you want to use digital assets for saving image its gives an error as below. anyone can help?

![digitalassest-cms1](https://user-images.githubusercontent.com/40492060/43570897-d33dd29c-963b-11e8-970d-9eb3a5a0c797.JPG)

**Comment by Aminshoshtaryzadeh** [comment]
hi @joewhite101 the latest version 5.1.0
here is the POM.XML file

[pom.docx](https://github.com/entando/entando-components/files/2252755/pom.docx)

**Comment by Aminshoshtaryzadeh** [comment]
there is another problem with cms, which has stop working and giving me error, so i cannot change the language and opening dropdown menu.

**Comment by joewhite101** [comment]
Hi @Aminshoshtaryzadeh do you have a screenshot or a stacktrace you can post? 

Also, if you are evaluating the platform you could consider using 5.0.1-SNAPSHOT. that is our next patch release and will be much more stable than master where we have active dev going on.

**Comment by Aminshoshtaryzadeh** [comment]
@joewhite101 
i am using default database derby, the thing is CMS plugin sometimes working and sometimes not.
I have to restart windows to work well. 
in next error i will send the screenshot as well.
but still i am not able to save any image in the platform by using assets image.
thank you.

**Comment by Aminshoshtaryzadeh** [comment]
This is the error that i get
![digitalassest-cms2](https://user-images.githubusercontent.com/40492060/43642809-4bfae01a-9729-11e8-85bc-af8181082a61.JPG)

**Comment by joewhite101** [comment]
Hey @Aminshoshtaryzadeh those errors aren't related to the digital assets upload. that is just because you are using the derby/jetty dev setup. I've just tried in our latest master builds and it is working correctly. Can you give it another shot with the latest jars

**Comment by Aminshoshtaryzadeh** [comment]
@joewhite101 I have tested new master build and the error has gone.
attachments working fine and they will show on the list but image will act blank and its not showing them on he resource.

**Comment by saberc** [comment]
Hi @Aminshoshtaryzadeh, In order to show the images you should install ImageMagick in your local machine.

**Comment by Aminshoshtaryzadeh** [comment]
@joewhite101 i mean in entando console like:
![digitalassest-cms3](https://user-images.githubusercontent.com/40492060/43966458-39ed333e-9cc2-11e8-9bea-054046313ed6.JPG)

![digitalassest-cms4](https://user-images.githubusercontent.com/40492060/43966464-3eab67c4-9cc2-11e8-8e24-799feb6c1bc0.JPG)


for this purpose i need to install imagemagik?

**Comment by Aminshoshtaryzadeh** [comment]
hi @joewhite101 
1- After using Entando Digital asset still i get an error for saving images as below:
kindly help me to resolve this issue.

2018-08-22 09:35:18.393 - ERROR - com.agiletec.plugins.jacms.aps.system.services.resource.ResourceManager - Error adding resources
com.agiletec.aps.system.exception.ApsSystemException: Error adding resource
        at com.agiletec.plugins.jacms.aps.system.services.resource.ResourceManager.addResource(ResourceManager.java:176)
        at com.agiletec.plugins.jacms.aps.system.services.resource.ResourceManager.lambda$addResources$0(ResourceManager.java:193)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at com.agiletec.plugins.jacms.aps.system.services.resource.ResourceManager.addResources(ResourceManager.java:191)
        at com.agiletec.plugins.jacms.apsadmin.resource.MultipleResourceAction.save(MultipleResourceAction.java:218)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at ognl.OgnlRuntime.invokeMethod(OgnlRuntime.java:873)
        at ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1539)
        at ognl.ObjectMethodAccessor.callMethod(ObjectMethodAccessor.java:68)
        at com.opensymphony.xwork2.ognl.accessor.XWorkMethodAccessor.callMethodWithDebugInfo(XWorkMethodAccessor.java:96)
        at com.opensymphony.xwork2.ognl.accessor.XWorkMethodAccessor.callMethod(XWorkMethodAccessor.java:88)
        at ognl.OgnlRuntime.callMethod(OgnlRuntime.java:1615)
        at ognl.ASTMethod.getValueBody(ASTMethod.java:91)
        at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
        at ognl.SimpleNode.getValue(SimpleNode.java:258)
        at ognl.Ognl.getValue(Ognl.java:467)
        at ognl.Ognl.getValue(Ognl.java:431)
        at com.opensymphony.xwork2.ognl.OgnlUtil$3.execute(OgnlUtil.java:351)
        at com.opensymphony.xwork2.ognl.OgnlUtil.compileAndExecuteMethod(OgnlUtil.java:403)
        at com.opensymphony.xwork2.ognl.OgnlUtil.callMethod(OgnlUtil.java:349)
        at com.opensymphony.xwork2.DefaultActionInvocation.invokeAction(DefaultActionInvocation.java:436)
        at com.opensymphony.xwork2.DefaultActionInvocation.invokeActionOnly(DefaultActionInvocation.java:291)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:252)
        at com.opensymphony.xwork2.interceptor.DefaultWorkflowInterceptor.doIntercept(DefaultWorkflowInterceptor.java:177)
        at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)
        at com.opensymphony.xwork2.validator.ValidationInterceptor.doIntercept(ValidationInterceptor.java:260)
        at org.apache.struts2.interceptor.validation.AnnotationValidationInterceptor.doIntercept(AnnotationValidationInterceptor.java:73)
        at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)
        at com.opensymphony.xwork2.interceptor.ConversionErrorInterceptor.doIntercept(ConversionErrorInterceptor.java:139)
        at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)
        at com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:133)
        at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)
        at com.opensymphony.xwork2.interceptor.StaticParametersInterceptor.intercept(StaticParametersInterceptor.java:192)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)
        at org.apache.struts2.interceptor.CheckboxInterceptor.intercept(CheckboxInterceptor.java:88)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)
        at org.apache.struts2.interceptor.debugging.DebuggingInterceptor.intercept(DebuggingInterceptor.java:253)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)
        at com.opensymphony.xwork2.interceptor.ChainingInterceptor.intercept(ChainingInterceptor.java:155)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)
        at org.apache.struts2.interceptor.I18nInterceptor.intercept(I18nInterceptor.java:120)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)
        at com.opensymphony.xwork2.interceptor.PrepareInterceptor.doIntercept(PrepareInterceptor.java:174)
        at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)
        at org.apache.struts2.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:171)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)
        at com.opensymphony.xwork2.interceptor.AliasInterceptor.intercept(AliasInterceptor.java:195)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)
        at com.opensymphony.xwork2.interceptor.ExceptionMappingInterceptor.intercept(ExceptionMappingInterceptor.java:193)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)
        at com.agiletec.apsadmin.system.BaseInterceptorMadMax.invoke(BaseInterceptorMadMax.java:119)
        at com.agiletec.apsadmin.system.InterceptorMadMax.invoke(InterceptorMadMax.java:104)
        at com.agiletec.apsadmin.system.BaseInterceptorMadMax.intercept(BaseInterceptorMadMax.java:63)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)
        at com.agiletec.apsadmin.system.BaseInterceptorMadMax.invoke(BaseInterceptorMadMax.java:119)
        at com.agiletec.apsadmin.system.BaseInterceptorMadMax.intercept(BaseInterceptorMadMax.java:63)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)
        at org.apache.struts2.interceptor.FileUploadInterceptor.intercept(FileUploadInterceptor.java:324)
        at com.agiletec.apsadmin.system.ApsFileUploadInterceptor.intercept(ApsFileUploadInterceptor.java:50)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)
        at org.apache.struts2.factory.StrutsActionProxy.execute(StrutsActionProxy.java:54)
        at org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:564)
        at org.apache.struts2.dispatcher.ExecuteOperations.executeAction(ExecuteOperations.java:81)
        at org.apache.struts2.dispatcher.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:143)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.entando.entando.aps.servlet.CORSFilter.doFilterInternal(CORSFilter.java:43)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.agiletec.aps.system.exception.ApsSystemException: Error saving image resource instances
        at com.agiletec.plugins.jacms.aps.system.services.resource.model.ImageResource.saveResourceInstances(ImageResource.java:131)
        at com.agiletec.plugins.jacms.aps.system.services.resource.ResourceManager.addResource(ResourceManager.java:171)
        ... 94 more
Caused by: com.agiletec.aps.system.exception.ApsSystemException: Error saving resized image resource instances
        at com.agiletec.plugins.jacms.aps.system.services.resource.model.ImageResource.saveResizedInstances(ImageResource.java:177)
        at com.agiletec.plugins.jacms.aps.system.services.resource.model.ImageResource.saveResourceInstances(ImageResource.java:122)
        ... 95 more
Caused by: com.agiletec.aps.system.exception.ApsSystemException: Error creating resource file instance 'cms/images/9f06826cdf1072b2bd596edbef2dca25_d1.jpg'
        at com.agiletec.plugins.jacms.aps.system.services.resource.model.ImageResource.saveResizedImage(ImageResource.java:228)
        at com.agiletec.plugins.jacms.aps.system.services.resource.model.ImageResource.saveResizedInstances(ImageResource.java:172)
        ... 96 more
Caused by: org.im4java.core.CommandException: org.im4java.core.CommandException: Invalid Parameter - -resize
        at org.im4java.core.ImageCommand.run(ImageCommand.java:215)
        at com.agiletec.plugins.jacms.aps.system.services.resource.model.ImageResource.saveResizedImage(ImageResource.java:219)
        ... 97 more
Caused by: org.im4java.core.CommandException: Invalid Parameter - -resize
        at org.im4java.core.ImageCommand.finished(ImageCommand.java:249)
        at org.im4java.process.ProcessStarter.run(ProcessStarter.java:314)
        at org.im4java.core.ImageCommand.run(ImageCommand.java:211)
        ... 98 more

---------------------------------------------------------------------------------------------------------------
2- Another issue is how i can address page model to custom css .
i have used as suggested in the text file by using : 
In this folder insert the CSS files for the frontend.
It's strongly suggested to create subfolders for:

- pagemodels/
- contentmodels/
- widgets/

The <wp:cssURL /> points to this folder.

so i used link tag as below:

<link rel="stylesheet" type="tag/text/css" href="<wp:cssURL />pagemodels/homepagecustom.css" media="screen" />
but still not working.
I will be appreciate if you guide me on this two issues.
